export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export type UserConstants = {
    USER_LOGIN_REQUEST: typeof USER_LOGIN_REQUEST;
    USER_LOGIN_SUCCESS: typeof USER_LOGIN_SUCCESS;
    USER_LOGIN_FAIL: typeof USER_LOGIN_FAIL;
    USER_LOGOUT: typeof USER_LOGOUT;
  };