import React from "react";
import { Head, Html, Main, NextScript } from "next/document";
import { type NextPage } from "next";

const Document: NextPage = () => {
  return (
    <Html lang="tr" dir="ltr">
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
